### ISSUE TITLE
Yiniitializr not aliased

### ISSUE THREAD

**Issue by P1xt** [tonydspaniard/yiinitializr-basic#3]
www/index.php throws an error on first startup because Yiinitializr isn't aliased.

Adding the line:

Yii::setPathOfAlias('Yiinitializr', './../../common/lib/Yiinitializr');

prior to the Initializer call fixes this

**Comment by tonydspaniard** [comment]
Thanks @roamingblue but is not the right solution... pushing the fix

**Comment by asyazwan** [comment]
Are we supposed to find `autoload.php` by ourselves? Because the file does not exist in the repository...

**Comment by tonydspaniard** [comment]
@asyazwan `autoload.php` is created automatically by composer. Do not worry about it, the template already points to it and will be there after you do the `composer install` command. 

References http://getcomposer.org/doc/01-basic-usage.md#autoloading
